language: python
python:
  - "3.6"
services:
  - docker

stages:
  - unit test
  - integration test
  - zap owasp test


jobs:
  include:
    #- stage: unit test
    #  script: pytest -k unit_test #Agregar modulo de pruebas unitarias
    #- stage: integration test
    #  script: pytest -k integration_test #Agregar modulo de pruebas de integracion
    - stage: zap owasp test
      script:
        - docker build -t felixurtubia/tps-restapi-repository .
        - docker run -d --name tps-restapi-repository -t felixurtubia/tps-restapi-repository
        - sleep 15
      after_script:
        - docker run --name owasp --link tps-restapi-repository -t owasp/zap2docker-weekly zap-full-scan.py -t http://localhost:5000

#Using heroku deploy 
deploy:
  provider: heroku
  api_key: 6d119b62-8c80-46c1-b021-b82dc30ca88e
  app: tps-restfulapi